### ISSUE TITLE
VS2017 compatibility

### ISSUE THREAD

**Issue by janspisiak** [ebruneton/precomputed_atmospheric_scattering#1]
Hi,
thanks for your demo, managed to make it run on Win32. Few problems were using constexpr variables as a result of trig functions (as they are not implemented to be constexpr, but it's a bug in gcc that it works). Replacing them with const works fine. M_PI needed to be defined, that's easy to define myself. Biggest problem were string literals when constructing shaders. There is a limit, I think 16kB, or even less in MSVC, so I had to split the std::string into multiple literals. Maybe better approach could be reading the file? Don't know.
Hope this helps somebody

**Comment by ebruneton** [comment]
Hi,

Thanks for your feedback. I'm working on Linux, could you send me a patch with your changes of const/constexpr? For string literals, does it work better if you replace the last lines of the makefile with

%.glsl.inc: %.glsl
	sed -e '1i const char* $(*F)_glsl = R"***(' -e '$$a )***";' $< > $@

i.e. by using "const char*" constants instead of string constants?

Eric

**Comment by ebruneton** [comment]
Closing this as "infeasible" (missing input from requester).
