### ISSUE TITLE
Is there any reason to start fading out light shaft so early?

### ISSUE THREAD

**Issue by 10110111** [ebruneton/precomputed_atmospheric_scattering#28]
Currently, when the Sun is 1° above horizon, the light shaft (and shadow) is already gone. This looks not nice, e.g. when you look at the sphere in the direction of the Sun (the shadowed part): the sphere seems to start glowing for a while until the Sun goes below horizon.

With `smoothstep` edges of `-0.026, -0.0035` instead of the current `0.02, 0.04` this looks much better but, when you look how the shadow extends into infinity, it goes into the sky:

![screenshot](https://user-images.githubusercontent.com/6376882/41178519-0acbfe6a-6b57-11e8-8364-caf0d705585b.jpg)

I suppose this is normal, given this real-life photo ([source](https://apod.nasa.gov/apod/ap111127.html)):

<img src="https://apod.nasa.gov/apod/image/1111/sts98plume_nasa_1111.jpg" height="400px" alt="real light shaft from smoke after sunset"><br/>

Of course, the light shaft in the demo looks a bit wrong due to the lack of penumbra and corresponding too sharp shape. But was this the only reason to avoid extending light shaft into the sky by too early fading out?

**Comment by ebruneton** [comment]
This was the main reason. The light shafts are computed with crude approximations. In particular, we assume there is no scattering at all in the shadow volume, whereas only single scattering is removed. Because of this, our light shafts are darker than they should be when multiple scattering dominates (i.e. when the Sun is low). To remove single scattering only, we would need to separate single and multiple scattering into separate precomputed textures, which would increase memory requirements and decrease the frame rate.

**Comment by 10110111** [comment]
Thanks for clarification.

**Comment by adrian173284** [comment]
hello eric bruneton how i can implement new atmosphere on application website even forking and implementing teach  me this procedure
